# Generated by Django 2.2.5 on 2019-10-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0003_auto_20191005_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='finish',
            field=models.DateTimeField(),
        ),
    ]
