# Generated by Django 2.2.5 on 2019-10-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0005_auto_20191005_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='finish',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
