# Generated by Django 2.2.5 on 2019-10-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0006_auto_20191006_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='img',
            field=models.ImageField(upload_to='mission_images/'),
        ),
    ]
