# Generated by Django 2.2.5 on 2019-10-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0009_auto_20191006_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='team_id',
            new_name='team',
        ),
    ]
