# Generated by Django 2.2.5 on 2019-10-05 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0012_auto_20191006_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerToCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie', models.ImageField(upload_to='selfieToCheck/')),
                ('place', models.ImageField(upload_to='placeToCheck/')),
                ('step', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game1.Team')),
            ],
        ),
    ]
