# Generated by Django 2.2.5 on 2019-10-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0018_auto_20191006_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertocheck',
            name='is_right',
        ),
    ]
