# Generated by Django 2.2.5 on 2019-10-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0019_remove_answertocheck_is_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertocheck',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='answertocheck',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
