# Generated by Django 2.2.5 on 2019-10-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0020_auto_20191006_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertocheck',
            name='is_right',
            field=models.BooleanField(null=True),
        ),
    ]
