# Generated by Django 2.2.5 on 2019-10-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0022_auto_20191006_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertocheck',
            name='is_right',
            field=models.NullBooleanField(default=True),
        ),
    ]
