# Generated by Django 2.2.5 on 2019-10-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0025_team_team_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
