# Generated by Django 2.2.5 on 2019-10-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0026_team_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='playerCount',
            field=models.IntegerField(default=0),
        ),
    ]
