# Generated by Django 2.2.5 on 2019-10-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0027_team_playercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertocheck',
            name='comment',
            field=models.CharField(default='Неправильные фотографии! Попробуйте сделать еще.', max_length=200),
        ),
    ]
